# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49849fdfc993cf62ca3b70fe1cc30d6e9e03f388fefaac9739902fede4cd968c10f51542ac17c8afed4a9f776e8878348dd1d08af58e06ff09b4ea519ae8f21

test:
  secret_key_base: 52aea43901d21ca1f55b13ae58a4f2f95f0d9dd7aa43675aabb53121f9645ad2c13fb390d2b2b9ca6a7d67d35a7fe0591cebdb255c20636b7bb226f8dd0a8746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
